SET TRAN ISOLATION LEVEL READ COMMITTED
BEGIN TRANSACTION
	SELECT dbo.HocSinh.DiaChi FROM dbo.HocSinh WHERE MaHS = 1
	UPDATE dbo.HocSinh SET DiaChi = 'Lam Dong' WHERE MaHS =1
	WAITFOR DELAY '00:00:10'


ROLLBACK


--T2
SET TRAN ISOLATION LEVEL READ COMMITTED 

BEGIN TRAN 
	SELECT dbo.HocSinh.DiaChi FROM dbo.HocSinh WHERE MaHS =1 
	
	
	COMMIT 