

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN 
DECLARE @TongSo FLOAT
SELECT @TongSo = dbo.ChiPhi.Tong FROM dbo.ChiPhi
WITH(UPDLOCK)
 WHERE MaChuyenDi = 'CD1'
WAITFOR DELAY '00: 00: 10'
UPDATE dbo.ChiPhi SET Tong = @TongSo + 10
SELECT dbo.ChiPhi.Tong FROM dbo.ChiPhi WHERE MaChuyenDi = 'CD1'
COMMIT



-- t2
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ

BEGIN TRAN 
DECLARE @TongSo FLOAT
SELECT @TongSo = dbo.ChiPhi.Tong FROM dbo.ChiPhi WITH(UPDLOCK)
  WHERE MaChuyenDi = 'CD1' 
UPDATE dbo.ChiPhi SET Tong = @TongSo + 20
COMMIT
SELECT dbo.ChiPhi.Tong FROM dbo.ChiPhi WHERE MaChuyenDi = 'CD1'