--CREATE DATABASE QLTV
USE QLTV
GO

CREATE TABLE DOCGIA
(
	MA_DOCGIA INT  PRIMARY KEY,
	HO NVARCHAR(10),
	TENLOT NVARCHAR(100),
	TEN NVARCHAR(100),
	NGAYSINH DATE
)
GO
CREATE TABLE NGUOILON
(
	MA_DOCGIA INT FOREIGN KEY REFERENCES dbo.DOCGIA(MA_DOCGIA),
	SONHA Nvarchar(50),
	DUONG NVARCHAR(100),
	QUAN NVARCHAR(50),
	DIENTHOAI VARCHAR(12),
	HAN_SD DATE,
	CONSTRAINT PK_NGUOILON PRIMARY KEY (MA_DOCGIA)
)
GO 

CREATE TABLE TREEM
(
	MA_DOCGIA INT FOREIGN KEY REFERENCES dbo.DOCGIA(MA_DOCGIA),
	MA_DOCGIA_NGUOILON INT FOREIGN KEY REFERENCES dbo.NGUOILON(MA_DOCGIA),
	CONSTRAINT PK_TREEM PRIMARY KEY (MA_DOCGIA)
)

GO
--DROP TABLE dbo.TREEM
CREATE TABLE TUASACH
(
	MA_TUASACH INT IDENTITY PRIMARY KEY,
	TUASACH NVARCHAR(100),
	TACGIA NVARCHAR(100),
	TOMTAT NVARCHAR(200)
)
GO



CREATE TABLE DAUSACH
(
	MA_DAUSACH INT IDENTITY PRIMARY KEY,
	MA_TUASACH INT FOREIGN KEY REFERENCES dbo.TUASACH(MA_TUASACH),
	NGONNGU NVARCHAR(100),
	BIA NVARCHAR(100),
	TRANGTHAI INT --0: KO THE CHO MUON. 1: CO THE MUON	
)
GO
CREATE TABLE CUONSACH
(
	MA_CUONSACH INT PRIMARY KEY,
	MA_DAUSACH INT FOREIGN KEY REFERENCES dbo.DAUSACH(MA_DAUSACH),
	TINHTRANG INT --0: KO CO SAN. 1: CO SAN

)
GO
--DROP TABLE dbo.CUONSACH
CREATE TABLE DANGKY
(
	MA_DAUSACH INT FOREIGN KEY REFERENCES dbo.DAUSACH(MA_DAUSACH),
	MA_DOCGIA INT FOREIGN KEY REFERENCES dbo.DOCGIA(MA_DOCGIA),
	NGAYGIO_DK DATETIME,
	GHICHU NVARCHAR(200),
	CONSTRAINT pk_DANGKY PRIMARY KEY(MA_DAUSACH,MA_DOCGIA)
)
GO
CREATE TABLE MUON
(
	MA_DAUSACH INT FOREIGN KEY REFERENCES dbo.DAUSACH(MA_DAUSACH),
	MA_CUONSACH INT FOREIGN KEY REFERENCES dbo.CUONSACH(MA_CUONSACH),
	MA_DOCGIA INT FOREIGN KEY REFERENCES dbo.DOCGIA(MA_DOCGIA),
	NGAYGIOMUON DATETIME,
	NGAY_HETHAN DATETIME,
	CONSTRAINT PK_MUON PRIMARY KEY(MA_DAUSACH,MA_CUONSACH)
)
GO
CREATE TABLE QUATRINHMUON
(
	MA_DAUSACH INT FOREIGN KEY REFERENCES dbo.DAUSACH(MA_DAUSACH),
	MA_CUONSACH INT FOREIGN KEY REFERENCES dbo.CUONSACH(MA_CUONSACH),
	NGAYGIO_MUON DATETIME,
	MA_DOCGIA INT FOREIGN KEY REFERENCES dbo.DOCGIA(MA_DOCGIA),
	NGAY_HETHAN DATETIME, 
	NGAY_TRA DATETIME,
	TIENMUON MONEY,
	TIEN_DATRA MONEY,
	TIEN_DATCOC MONEY,
	GHICHU NVARCHAR(200),
	CONSTRAINT PK_QTMUON PRIMARY KEY(MA_DAUSACH,MA_CUONSACH,NGAYGIO_MUON)
)
GO