--phantom
--T1
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN
	SELECT SUM(SoTien) FROM dbo.ThongTinThanhToan WHERE MaHopDong=N'HD1'
	WAITFOR DELAY '00:00:05'
	SELECT SUM(SoTien) FROM dbo.ThongTinThanhToan WHERE MaHopDong=N'HD1'
COMMIT
